portfolio/views.py
from flask import render_template, abort, Blueprint
from route_manager import RouteManager

views = Blueprint('views', __name__)
manager = RouteManager()

# route declarations
# load last 4 (or whatever) posts as child templates into home page
@views.route('/')
def load_index():
    projects = manager.get_n_projects('project', 4)
    articles = manager.get_n_projects('article', 2)
    # need to add 'no pages found'
    data = {
        'projects': projects,
        'articles': articles
    }
    return render_template('index.html', data=data)

@views.route('/projects/')
def load_projects():
    projects = manager.all_projects_bytype()
    return render_template('projects.html', data=projects)

@views.route('/articles/')
def load_articles():
    articles = manager.get_n_projects('article')
    return render_template('articles.html', data=articles)

# TODO come up with clear definitions for projects vs articles or other
# entities - clean up data and either make everything one type or
# abstract things in a more reasonable way
@views.route('/project/<id>')
def load_project(id):
    project = manager.get_project_byid(id)
    template = project['template']
    if template:
        return render_template(template, data=project)
    else:
        abort(404)

@views.route('/article/<id>')
def load_article(id):
    article = manager.get_project_byid(id)
    template = article['template']
    if template:
        return render_template(template, data=article)
    else:
        abort(404)

portfolio/templates/articles.html
{% extends "base.html" %}

{% block title %}All Articles{% endblock %}

{% block content %}

    <div class="content all-projects">

        <h3 class="categories">articles</h3>

    {% for d in data %}

        <p class="project">
            <a href="{{ url_for('views.load_article', id=d['name']) }}">{{ d['title'] }}</a>

            {% if d['timestamp'] %}
                <span>Posted: {{ d['timestamp'] }}</span>
            {% endif %}

            {% if d['updated'] %}
                <span>Updated: {{ d['updated'] }}</span>
            {% endif %}

        </p>

    {% endfor %}

    </div>

{% endblock %}

portfolio/templates/base.html
<!doctype html>
<html>

<head>
    {% block head %}

    <title>{% block title %}Portfolio{% endblock %}</title>
<!-- main styles go here -->
    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/magula.min.css">
    {% endblock %}

    {% block scripts %}
<!-- main scripts go here -->
    <script src="{{ url_for('static', filename='js/libs/jquery-1.10.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/libs/underscore-min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/libs/raphael.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>
    <script>
        hljs.configure({
            languages: [ 'javascript', 'html', 'css', 'bash', 'python', 'json' ]
        });
        hljs.initHighlightingOnLoad();
    </script>

    {% endblock %}

    {% endblock %}
</head>

<body>

    <section class="main-container">

        <header>
        {% block header %}

            <h1>{% block main_title %}M. Beckwith{% endblock %}</h1>

            {% block navigation %}
            <ul class="main-menu">
                <li><a href="{{ url_for('views.load_index') }}">Home</a></li>
                <li><a href="{{ url_for('views.load_projects') }}">Projects</a></li>
                <li><a href="{{ url_for('views.load_articles') }}">Articles</a></li>
            </ul>
            {% endblock %}


        {% endblock %}
        </header>

        <section class="container">
        {% block content %}

        {% endblock %}
        </section>

        <footer>
        {% block footer %}
            <h6>
                <span class="copyright">&copy; 2013 Ming Beckwith</span>
                <span class="info">
                    Built with{{ " " }}<a href="http://flask.pocoo.org/">Flask</a>{{ " " }}and{{ " " }}<a href="http://redis.io/">Redis</a>{{ " " }}
                    Hosted on{{ " " }}<a href="http://aws.amazon.com/">Amazon Web Services</a>
                </span>
            </h6>
        {% endblock %}
        </footer>

    </section>

</body>

</html>

portfolio/templates/bokeh.html
{% extends "base.html" %}

{% block title %}{{ data['title'] }}{% endblock %}

{% block styles %}

    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bokeh.css') }}">

{% endblock %}

{% block scripts %}

    {{ super() }}
    <script src="{{ url_for('static', filename='js/bokeh/bokeh.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bokeh/bokeh-demo.js') }}"></script>

{% endblock %}

{% block content %}

    <section class="content">

        <section class="project-info">
            <h2>{{ data['title'] }}</h2>
            <p class="post-date">Posted: {{ data['timestamp'] }}</p>
            <p class="project-description">
                A simple SVG bokeh generator made with{{ " " }}<a href="http://raphaeljs.com/">Raphael</a>{{ " and " }}<a href="http://documentcloud.github.io/underscore/">Underscore</a>.
            </p>
        </section>
        <section id="bokeh-canvas" class="dark-background"></section>
        <section id="bokeh-controls">
            <fieldset>
                <label for="bg-switcher">Dark Background</label>
                <input type="checkbox" name="bg-switcher" id="bg-switcher" checked>
                <button id="generate">Generate Bokeh</button>
            </fieldset>
        </section>

    </section>

{% endblock %}

portfolio/templates/index.html
{% extends "base.html" %}

{% block title %}Main Page{% endblock %}

{% block content %}

    <section class="content">

        <div class="recent-projects">

            <h3>recent projects</h3>

        {% for value in data['projects'] %}

                <div class="project">

                    {% if value['preview'] %}
                        <div class="project-preview">
                            <img src="{{ url_for('static', filename='images/' + value['preview']) }}">
                        </div>
                    {% endif %}

                    <div class="project-meta">
                        <a href="{{ url_for('views.load_project', id=value['name']) }}">{{ value['title'] }}</a>

                        {% if value['timestamp'] %}
                            <p class="meta">Posted: {{ value['timestamp'] }}</p>
                        {% endif %}

                        {% if value['updated'] %}
                            <p class="meta">Updated: {{ value['updated'] }}</p>
                        {% endif %}
                    </div>

                </div>

        {% endfor %}

        </div>

        <div class="recent-articles">

            <h3>recent articles</h3>

            {% for value in data['articles'] %}

                    <div>

                        <div class="project-meta">
                            <a href="{{ url_for('views.load_article', id=value['name']) }}">{{ value['title'] }}</a>

                            {% if value['timestamp'] %}
                                <p class="meta">Posted: {{ value['timestamp'] }}</p>
                            {% endif %}

                            {% if value['updated'] %}
                                <p class="meta">Updated: {{ value['updated'] }}</p>
                            {% endif %}
                        </div>

                    </div>

            {% endfor %}

        </div>

    </section>

{% endblock %}

portfolio/templates/jenkins.html
{% extends "base.html" %}

{% block title %}{{ data['title'] }}{% endblock %}

{% block styles %}

    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/code.css') }}">

{% endblock %}

{% block scripts %}

    {{ super() }}

{% endblock %}

{% block content %}

    <section class="content toggleshow">

        <section class="project-info">
            <h2>{{ data['title'] }}</h2>
            <p class="post-date">Posted: {{ data['timestamp'] }}</p>
            <p class="project-description">
                I recently became interested in automating my JavaScript unit tests as part of a {{ " " }}<a href="http://en.wikipedia.org/wiki/Continuous_integration">continuous integration</a>{{ " " }} build. Of course to accomplish that I needed to first install a CI server locally to {{ " " }}<span class="strike">break</span>{{ " " }} play with. I decided to use {{ " " }}<a href="http://jenkins-ci.org/">Jenkins</a>{{ " " }} since that is the main CI server I'm familiar with, it's open source (hurrah!), and there's great docs/plugins/online support.
            </p>
            <p class="project-description">
                A lot of the articles I found on how to install Jenkins on OSX were several years old so I documented my own install process... and here it is:
            </p>
            <h4>Stuff you need (AKA what I used):</h4>
            <p class="aside">Exact versions given where possible</p>
            <ul class="technical-list">
                <li>Mac OSX 10.8.4</li>
                <li>Jenkins 1.5.48</li>
                <li>Java 1.5+</li>
            </ul>
        </section>

        <section class="article">
            <p>
                First, make sure you don't have anything running on port 8080 because Jenkins will use that by default. Then, download the installer and run it: {{ " " }}<a href="http://mirrors.jenkins-ci.org/osx/latest">http://mirrors.jenkins-ci.org/osx/latest</a>
            </p>
            <p>
                Accept all the default options except "Installation Type". Here click "customize" and make sure "start at boot as jenkins" is checked and "start at boot as daemon" is not.
            </p>
            <p>If everything goes well, Jenkins will launch (probably in Safari) at {{ " " }}<a href="http://localhost:8080">http://localhost:8080</a></p>
            <p>Easy peasy right?</p>
            <h4>A few paths worth knowing:</h4>
            <ul class="technical-list">
                <li>Jenkins will be installed at {{ " " }}<code>/Users/Shared/Jenkins</code></li>
                <li>The launch daemon is at {{ " " }}<code>/Library/LaunchDaemons/org.jenkins-ci.plist</code></li>
                <li>Preferences are at {{ " " }}<code>/Library/Preferences</code></li>
            </ul>
        </section>

        <section class="article">
            <p>Jenkins can run via the launch daemon or by executing the war file found at /Applications/Jenkins. I used the launch daemon.</p>
            <div class="snippet">
                <p>If you choose to use the war file you can execute it with:</p>
                <pre><code>java -jar /Applications/Jenkins/jenkins.war [options]</code></pre>
        </div>
        <div class="snippet">
            <p>To stop Jenkins:</p>
            <pre><code>sudo launchctl unload /Library/LaunchDaemons/org.jenkins-ci.plist</code></pre>
        </div>
        <div class="snippet">
            <p>And to start:</p>
            <pre><code>sudo launchctl load /Library/LaunchDaemons/org.jenkins-ci.plist</code></pre>
        </div>
        <div class="snippet">
            <p>To see the default configuration:</p>
            <pre><code>sudo launchctl load /Library/LaunchDaemons/org.jenkins-ci.plist</code></pre>
        </div>
        <div class="snippet">
            <p>To change the default configuration:</p>
            <pre><code>defaults write /Library/Preferences/org.jenkins-ci [setting] [value]</code></pre>
        </div>
        <div class="snippet">
            <p>Lets change the default port to something else since 8080 is frequently used by other apps:</p>
            <pre><code># make sure Jenkins is stopped
sudo launchctl unload /Library/LaunchDaemons/org.jenkins-ci.plist
defaults write /Library/Preferences/org.jenkins-ci httpPort 8888
# restart
sudo launchctl load /Library/LaunchDaemons/org.jenkins-ci.plist</code></pre>
        </div>
        <p>Now go to {{ " " }}<a href="http://localhost:8888">http://localhost:8888</a>{{ " " }} in your favorite browser and the Jenkins UI should appear.</p>
        <p>
            Additional settings supported by the launch daemon can be seen here: {{ " " }}
                <a href="https://wiki.jenkins-ci.org/display/JENKINS/Thanks+for+using+OSX+Installer">https://wiki.jenkins-ci.org/display/JENKINS/Thanks+for+using+OSX+Installer</a>
        </p>
        </section>

    </section>

{% endblock %}

portfolio/templates/projects.html
{% extends "base.html" %}

{% block title %}All Projects{% endblock %}

{% block content %}

    <div class="content all-projects">

    {% for d in data %}
        <h3 class="categories">{{ d }}s</h3>

        {% for project in data[d] %}
            <p class="project">
                <a href="{{ url_for('views.load_project', id=project['name']) }}">{{ project['title'] }}</a>

                {% if project['timestamp'] %}
                    <span>Posted: {{ project['timestamp'] }}</span>
                {% endif %}

                {% if project['updated'] %}
                    <span>Updated: {{ project['updated'] }}</span>
                {% endif %}

            </p>
        {% endfor %}

    {% endfor %}

    </div>

{% endblock %}

portfolio/templates/scraper.html
{% extends "base.html" %}

{% block title %}{{ data['title'] }}{% endblock %}

{% block styles %}

    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/scraper.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/tooltip.css') }}">

{% endblock %}

{% block scripts %}

    {{ super() }}
    <script src="{{ url_for('static', filename='js/libs/d3.v3.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scraper/scraper.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scraper/scraper-demo.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tooltip/tooltip.js') }}"></script>

{% endblock %}

{% block content %}

    <section class="content scraper">

        <section class="project-info">
            <h2>{{ data['title'] }}</h2>
            <p class="post-date">Posted: {{ data['timestamp'] }}</p>
            <p class="project-description">
                A description will go here
            </p>
        </section>

        <section id="demo-container"></section>

    </section>

{% endblock %}

portfolio/templates/toggleshow.html
{% extends "base.html" %}

{% block title %}{{ data['title'] }}{% endblock %}

{% block styles %}

    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/toggleshow.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/code.css') }}">

{% endblock %}

{% block scripts %}

    {{ super() }}
    <script src="{{ url_for('static', filename='js/toggleshow/toggleshow.js') }}"></script>

    <script>

        $(document).ready(function() {

            $('#toggleshow').toggleshow();

            $('.toggleshow2').toggleshow();

            $('.toggleshow3').toggleshow({
                mapContainers: [
                    {
                        main: '.toggleshow3',
                        inner: '.container1 .container2',
                        largeIcon: true
                    },
                    {
                        main: '.container1',
                        inner: '.child1',
                        largeIcon: false
                    },
                    {
                        main: '.child1',
                        inner: 'p .child2',
                        largeIcon: true
                    },
                    {
                        main: '.child2',
                        inner: 'p',
                        largeIcon: false
                    },
                    {
                        main: '.container2',
                        inner: 'p'
                    }
                ]
            });

        });

    </script>

{% endblock %}

{% block content %}

    <section class="content toggleshow">

        <section class="project-info">
            <h2>{{ data['title'] }}</h2>
            <p class="post-date">Posted: {{ data['timestamp'] }}</p>
            <p class="project-description">
                A{{ " " }}<a href="http://jquery.com/">jQuery</a>{{ " " }}plugin for toggling unlimited levels of content. The plugin is minimally styled to be simple to customize and can support most markup structures including tables.
            </p>
            <div class="downloads">
                <p>JavaScript:{{ " " }}<a href={{ data['js'] }}>{{ data['js'] }}</a></p>
                <p>CSS:{{ " "  }}<a href={{ data['css'] }}>{{ data['css'] }}</a></p>
            </div>
        </section>

        <section class="toggleshow-demo">

            <div class="project-description">
                If no options are passed, calling the plugin on an element will make that the top level container. All divs that are descendents of the top level container will also become containers.
            </div>

            <div class="example">
                <p class="demo-description">
                    A basic example with default options:
                </p>
                <div class="demo">
                    <div id="toggleshow">
                        parent
                        <div>
                            child one
                            <p>inner content</p>
                        </div>
                        <div>
                            child two
                        </div>
                    </div>
                </div>
                <div class="code">
                    <pre><code>$('#toggleshow').toggleshow();</code></pre>
<!--                    <pre><code>
&lt;div id="toggleshow"&gt;
    parent
    &lt;div&gt;
        child one
        &lt;p&gt;inner content&lt;/p&gt;
    &lt;/div&gt;
    &lt;div&gt;
        child two
    &lt;/div&gt;
&lt;/div&gt;
                    </code></pre>-->
                </div>
            </div>

            <div class="example">
                <p class="demo-description">
                    Call the plugin on multiple elements using a class name:
                </p>
                <div class="demo">
                    <div class="toggleshow2">
                        parent 1
                        <div>
                            child one
                            <p>
                                inner content
                            </p>
                        </div>
                        <div>
                            child two
                        </div>
                    </div>
                    <div class="toggleshow2">
                        parent 2
                        <div>
                            child one
                            <p>
                                inner content
                            </p>
                        </div>
                        <div>
                            child two
                        </div>
                    </div>
                </div>
                <div class="code">
                    <pre><code>$('.toggleshow2').toggleshow();</code></pre>
<!--                    <pre><code>
&lt;div class="toggleshow2"&gt;
    parent 1
    &lt;div&gt;
        child one
        &lt;p&gt;
            inner content
        &lt;/p&gt;
    &lt;/div&gt;
    &lt;div&gt;
        child two
    &lt;/div&gt;
&lt;/div&gt;
&lt;div class="toggleshow2"&gt;
    parent 2
    &lt;div&gt;
        child one
        &lt;p&gt;
            inner content
        &lt;/p&gt;
    &lt;/div&gt;
    &lt;div&gt;
        child two
    &lt;/div&gt;
&lt;/div&gt;
                    </code></pre> -->
                </div>
            </div>

            <div class="example">
                <p class="demo-description">
                    A more complex markup structure using the mapContainers option:
                </p>
                <div class="demo">
                    <div class="toggleshow3">
                        parent 1
                        <div class="container1">
                            container 1
                            <div class="child1">
                                child 1
                                <p>inner content</p>
                                <div class="child2">
                                    child two
                                    <p>inner content</p>
                                </div>
                            </div>
                        </div>
                        <div class="container2">
                            container 2
                            <p>inner content</p>
                        </div>
                    </div>
                </div>
                <div class="code">
                    <pre><code>$('.toggleshow3').toggleshow({
    mapContainers: [
        {
            main: '.toggleshow3',
            inner: '.container1 .container2',
            largeIcon: true
        },
        {
            main: '.container1',
            inner: '.child1',
            largeIcon: false
        },
        {
            main: '.child1',
            inner: 'p .child2',
            largeIcon: true
        },
        {
            main: '.child2',
            inner: 'p',
            largeIcon: false
        },
        {
            main: '.container2',
            inner: 'p'
        }
    ]
});</code></pre>
                </div>
            </div>

            <p>Options:</p>
            <table>
                <thead>
                    <tr>
                        <th>Option</th>
                        <th>Type</th>
                        <th>Default Value</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>mapContainers</td>
                        <td>Array</td>
                        <td>null</td>
                        <td>An array of configuration objects indicating how elements should be nexted. Each object should have a 'main' property which is a string selector for the container and an 'inner' property which is a string selector of the children which should be hidden/shown by toggling the parent. There is an optional 'largeIcon' property (boolean) which determines whether the larger or smaller arrow is used as the icon. By default the top level container has a large arrow icon and all others are small.</td>
                    </tr>
                    <tr>
                        <td>imageSource</td>
                        <td>Object</td>
                        <td>null</td>
                        <td>An object with paths to the icon images. There should be four properties: containerOff, containerOn, childrenOff, and childrenOn. The plugin will add containerOn/Off images to the outmost parent element or to any elements specified by the containerMap. childrenOn/Off images will be added to all inner containers or as specified by the map. On is for the toggled open state, off indicates the container is toggled shut.</td>
                    </tr>
                </tbody>
            </table>

            <p>Methods:</p>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>expand</td>
                        <td>Open all containers.</td>
                    </tr>
                    <tr>
                        <td>contract</td>
                        <td>Closes all containers.</td>
                    </tr>
                </tbody>
            </table>

        </section>

    </section>

{% endblock %}